services:
  caddy:
    image: ${CADDY_IMAGE}
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - TZ=${TZ}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Caddy stores certs here (IMPORTANT: include in backups)
      - ${VOL_CADDY_DATA}:/data:Z
      - ${VOL_CADDY_CONFIG}:/config:Z
    restart: unless-stopped
    networks:
      - shared-network
    

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    volumes:
      - ${VOL_POSTGRES}:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - shared-network

  redis:
    # I'd strongly recommend Redis 7; but keeping your env var as-is
    image: ${REDIS_IMAGE}
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1000"]
    volumes:
      - ${VOL_REDIS}:/data:Z
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - shared-network

  n8n:
    image: ${N8N_IMAGE}
    container_name: n8n
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - TZ=${TZ}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}

      # Optional for future queue mode
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379

      - NODE_OPTIONS=--max-old-space-size=${N8N_MAX_OLD_SPACE_SIZE}
      - N8N_DIAGNOSTICS_ENABLED=false
      - GENERIC_TIMEZONE=${TZ}
    volumes:
      - ${VOL_N8N}:/home/node/.n8n:Z
    restart: unless-stopped
    networks:
      - shared-network

volumes:
  caddy_data:
    name: ${VOL_CADDY_DATA}
  caddy_config:
    name: ${VOL_CADDY_CONFIG}
  pgdata:
    name: ${VOL_POSTGRES}
  n8n_data:
    name: ${VOL_N8N}
  redis_data:
    name: ${VOL_REDIS}

networks:
  shared-network:
    external: true